dirpath: '${work_dir}/checkpoints/${now:%Y-%m-%d_%H%M%S}'

model_checkpoint_1:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: 'val_acc'
  dirpath: ${dirpath}
  filename: 'model-{epoch:02d}-{val_acc:.2f}'
  save_top_k: 3
  mode: 'max'

  #verbose: False
  save_last: True
  #save_weights_only: False
  #auto_insert_metric_name: True
  #every_n_train_steps: null
  #train_time_interval: null
  #every_n_epochs: null 
  #save_on_train_epoch_end: null

model_checkpoint_2:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: 'val_loss'
  dirpath: ${dirpath}
  filename: 'model-{epoch:02d}-{val_loss:.2f}'
  save_top_k: 3
  mode: 'min'

  #verbose: False
  save_last: True
  #save_weights_only: False
  #auto_insert_metric_name: True
  #every_n_train_steps: null
  #train_time_interval: null
  #every_n_epochs: null 
  #save_on_train_epoch_end: null

early_stopping:
  _target_: pytorch_lightning.callbacks.early_stopping.EarlyStopping
  monitor: 'val_loss'
  patience: 10
  mode: 'min'

  #min_delta: 0.0
  #verbose: False
  #strict: True 
  #check_finite: True 
  #stopping_threshold: null 
  #divergence_threshold: null 
  #check_on_train_epoch_end: null 
  #log_rank_zero_only: False