model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: 'val_acc'
  dirpath: '${work_dir}/checkpoints/'
  filename: 'model-{epoch:02d}-{val_acc:.2f}'
  save_top_k: 3
  mode: 'max'

early_stopping:
  _target_: pytorch_lightning.callbacks.early_stopping.EarlyStopping
  monitor: 'val_loss'
  patience: 10
  mode: 'min'