hydra:
  run:
    dir: logs/hydra/${experiment}/${now:%Y-%m-%d_%H%M%S}

experiment: baseline
work_dir: ${hydra:runtime.cwd}
num_classes: 6
model_version: 'B0'

defaults:
  - _self_
  - model: efficientnet
  - data: trashnet_datamodule
  - lightning_module: efficientnet_model
  - callbacks: default
  - logger: wandb

trainer:
  max_epochs: 70 
  accelerator: 'gpu'
  devices: 1
  log_every_n_steps: 32
  ckpt_path: null