_target_: pytorch_lightning.loggers.WandbLogger

project: 'gsn-garbage-classification' 
job_type: 'train'
save_dir: ${work_dir}/logs
tags: ['${experiment}', '${model_version}', 'batch_size=${data.batch_size}']